import { Role, ApprovalStatus, VerificationStatus } from '@prisma/client';

export const FALLBACK_USERS: any[] = [
  {
    id: 'usr-farmer-1',
    name: 'Ramesh Patel',
    phone: '9876543210',
    email: 'ramesh@farmer.in',
    password: 'Farmer@123',
    role: Role.FARMER,
    verificationStatus: VerificationStatus.VERIFIED,
    approvalStatus: ApprovalStatus.APPROVED,
    rejectionReason: null,
    approvedBy: 'usr-admin-1',
    approvedAt: new Date(),
    district: 'Nashik',
    state: 'Maharashtra',
    village: 'Pimpalgaon Baswant',
    location: 'Village Pimpalgaon, Niphad Taluka, Nashik',
    primaryCrop: 'Tomato',
    farmSize: 8.5,
    preferredLanguage: 'en',
    organization: null,
    contactPerson: null,
    businessType: null,
    warehouseLocation: null,
    gstin: null,
    fssai: null,
    kccNumber: 'KCC-MAH-992144',
    apmcLicense: 'APMC-NSK-TRD-401',
    isVerified: true,
    createdAt: new Date(Date.now() - 86400000 * 10),
  },
  {
    id: 'usr-farmer-2',
    name: 'Gurpreet Singh',
    phone: '9876543211',
    email: 'gurpreet@farmer.in',
    password: 'Farmer@123',
    role: Role.FARMER,
    verificationStatus: VerificationStatus.VERIFIED,
    approvalStatus: ApprovalStatus.APPROVED,
    rejectionReason: null,
    approvedBy: 'usr-admin-1',
    approvedAt: new Date(),
    district: 'Ludhiana',
    state: 'Punjab',
    village: 'Khanna Kalan',
    location: 'Khanna Mandi Road, Ludhiana',
    primaryCrop: 'Wheat',
    farmSize: 15.0,
    preferredLanguage: 'en',
    organization: null,
    contactPerson: null,
    businessType: null,
    warehouseLocation: null,
    gstin: null,
    fssai: null,
    kccNumber: 'KCC-PJB-881290',
    apmcLicense: 'APMC-LDH-TRD-102',
    isVerified: true,
    createdAt: new Date(Date.now() - 86400000 * 8),
  },
  {
    id: 'usr-buyer-1',
    name: 'FreshCart Agro Ltd.',
    phone: '9876543212',
    email: 'buyer@freshcart.com',
    password: 'asdfcv321',
    role: Role.BUYER,
    verificationStatus: VerificationStatus.VERIFIED,
    approvalStatus: ApprovalStatus.APPROVED,
    rejectionReason: null,
    approvedBy: 'usr-admin-1',
    approvedAt: new Date(),
    district: 'Mumbai',
    state: 'Maharashtra',
    village: null,
    location: 'Vashi APMC Complex, Navi Mumbai',
    primaryCrop: null,
    farmSize: null,
    preferredLanguage: 'en',
    organization: 'FreshCart Agro Limited',
    contactPerson: 'Praveen Kumar',
    businessType: 'Wholesale Food Processor',
    warehouseLocation: 'Vashi APMC Sector 19, Navi Mumbai',
    gstin: '27AABCU9603R1ZM',
    fssai: '10019022009876',
    kccNumber: null,
    apmcLicense: 'APMC-VSH-BYR-550',
    isVerified: true,
    createdAt: new Date(Date.now() - 86400000 * 7),
  },
  {
    id: 'usr-buyer-2',
    name: 'GreenSpire Foods',
    phone: '9876543213',
    email: 'procurement@greenspire.in',
    password: 'asdfcv321',
    role: Role.BUYER,
    verificationStatus: VerificationStatus.VERIFIED,
    approvalStatus: ApprovalStatus.APPROVED,
    rejectionReason: null,
    approvedBy: 'usr-admin-1',
    approvedAt: new Date(),
    district: 'Delhi',
    state: 'Delhi',
    village: null,
    location: 'Azadpur Trade Terminal, North Delhi',
    primaryCrop: null,
    farmSize: null,
    preferredLanguage: 'en',
    organization: 'GreenSpire Food Processors Pvt Ltd',
    contactPerson: 'Anil Sharma',
    businessType: 'Institutional Procurement',
    warehouseLocation: 'Azadpur Terminal Gate 4, Delhi',
    gstin: '07AAECG8812K1Z9',
    fssai: '10021011003412',
    kccNumber: null,
    apmcLicense: 'APMC-AZD-BYR-219',
    isVerified: true,
    createdAt: new Date(Date.now() - 86400000 * 5),
  },
  {
    id: 'usr-admin-1',
    name: 'Vanijya System Admin',
    phone: '9876543214',
    email: 'admin@vanijya.gov.in',
    password: 'Admin@123',
    role: Role.ADMIN,
    verificationStatus: VerificationStatus.VERIFIED,
    approvalStatus: ApprovalStatus.APPROVED,
    rejectionReason: null,
    approvedBy: 'SYSTEM',
    approvedAt: new Date(),
    district: 'New Delhi',
    state: 'Delhi',
    village: null,
    location: 'Ministry of Agriculture, Krishi Bhawan, New Delhi',
    primaryCrop: null,
    farmSize: null,
    preferredLanguage: 'en',
    organization: 'Ministry of Agriculture & Farmers Welfare',
    contactPerson: 'Director General',
    businessType: 'Government Oversight',
    warehouseLocation: null,
    gstin: null,
    fssai: null,
    kccNumber: null,
    apmcLicense: null,
    isVerified: true,
    createdAt: new Date(Date.now() - 86400000 * 30),
  },
];
